### ISSUE TITLE
Industrialization

### ISSUE THREAD

**Issue by nvuillam** [davegallant/docker-groovy-lint#2]
Thanks for the repo :)

I have some requests, if you allow me , please could you : 
- Upload the docker image to docker hub
- Allow to send custom arguments when calling the docker image
- Add a documentation with example about how to use this image in : 
  - A Jenkins job
  - A Circle CI job

You can continue here, or also migrate to npm-groovy-lint repo with a PR ^^

Thanks :)

**Comment by davegallant** [comment]
@nvuillam I can work on this and then create a PR in https://github.com/nvuillam/npm-groovy-lint

**Comment by nvuillam** [comment]
Great, thanks for the groovy community :)
